"""Add admin invitations

Revision ID: 01ad09c46214
Revises: 51657a536247
Create Date: 2026-08-07 11:47:28.830158

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01ad09c46214'
down_revision: Union[str, Sequence[str], None] = '51657a536247'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_invitations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['admins.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index(op.f('ix_admin_invitations_admin_id'), 'admin_invitations', ['admin_id'], unique=False)
    op.create_index(op.f('ix_admin_invitations_id'), 'admin_invitations', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_admin_invitations_id'), table_name='admin_invitations')
    op.drop_index(op.f('ix_admin_invitations_admin_id'), table_name='admin_invitations')
    op.drop_table('admin_invitations')
    # ### end Alembic commands ###
