"""add admin password resets

Revision ID: 76909875d99f
Revises: 2c35ff7bba77
Create Date: 2026-08-11 05:08:05.679766

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76909875d99f'
down_revision: Union[str, Sequence[str], None] = '2c35ff7bba77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_password_resets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['admins.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index(op.f('ix_admin_password_resets_admin_id'), 'admin_password_resets', ['admin_id'], unique=False)
    op.create_index(op.f('ix_admin_password_resets_id'), 'admin_password_resets', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_admin_password_resets_id'), table_name='admin_password_resets')
    op.drop_index(op.f('ix_admin_password_resets_admin_id'), table_name='admin_password_resets')
    op.drop_table('admin_password_resets')
    # ### end Alembic commands ###
