"""Add admin OTPs

Revision ID: 769b9e0ccabc
Revises: bec222a11862
Create Date: 2026-08-07 09:21:18.178148

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '769b9e0ccabc'
down_revision: Union[str, Sequence[str], None] = 'bec222a11862'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_otps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=False),
    sa.Column('otp_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['admins.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_otps_admin_id'), 'admin_otps', ['admin_id'], unique=False)
    op.create_index(op.f('ix_admin_otps_id'), 'admin_otps', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_admin_otps_id'), table_name='admin_otps')
    op.drop_index(op.f('ix_admin_otps_admin_id'), table_name='admin_otps')
    op.drop_table('admin_otps')
    # ### end Alembic commands ###
