"""Add admin table

Revision ID: bec222a11862
Revises: ed89d41c1d7f
Create Date: 2026-08-07 08:05:42.106900

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bec222a11862'
down_revision: Union[str, Sequence[str], None] = 'ed89d41c1d7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admins', sa.Column('hashed_password', sa.String(length=255), nullable=False))
    op.add_column('admins', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.create_index(op.f('ix_admins_id'), 'admins', ['id'], unique=False)
    op.drop_column('admins', 'name')
    op.drop_column('admins', 'password_hash')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admins', sa.Column('password_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('admins', sa.Column('name', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_admins_id'), table_name='admins')
    op.drop_column('admins', 'is_active')
    op.drop_column('admins', 'hashed_password')
    # ### end Alembic commands ###
