"""Add email to registrations

Revision ID: ed89d41c1d7f
Revises: f48beed0e29e
Create Date: 2026-08-07 06:39:40.753248

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed89d41c1d7f'
down_revision: Union[str, Sequence[str], None] = 'f48beed0e29e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "registrations",
        sa.Column(
            "email",
            sa.String(length=255),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('registrations', 'email')
    # ### end Alembic commands ###
